export const oracleTypes = [
    "history",
    "science",
    "technology",
    "mythology",
    "philosophy",
    "astrology",
    "psychology",
    "sociology",
    "literature",
    "art",
    "religion",
    "politics",
    "economics",
    "astronomy",
    "geography",
    "environment",
    "health",
    "education",
    "law",
    "culture",
    "entertainment",
    "sports",
    "travel",
    "music",
    "cuisine"
  ] as const;